name       : haskell-unliftio
version    : 0.2.7.0
release    : 1
source     :
    - http://hackage.haskell.org/package/unliftio-0.2.7.0/unliftio-0.2.7.0.tar.gz : 5adaf4c623914ec027760259042059326c14831e8c9142287cf8f082e9481463
license    : MIT
component  : programming.haskell
summary    : The MonadUnliftIO typeclass for unlifting monads to IO (batteries included)
description: |
    The MonadUnliftIO typeclass for unlifting monads to IO (batteries included)
builddeps  :
    - haskell-async
    - haskell-cabal-install
    - haskell-stm
    - haskell-unliftio-core
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
