name       : haskell-unliftio
version    : 0.2.13
release    : 2
source     :
    - https://hackage.haskell.org/package/unliftio-0.2.13/unliftio-0.2.13.tar.gz : c2562c4c32a1a3ce4ad10c9e5c816862858c80cec0340599747e4dca586ef9f3
license    : MIT
component  : programming.haskell
summary    : The MonadUnliftIO typeclass for unlifting monads to IO (batteries included)
description: |
    The MonadUnliftIO typeclass for unlifting monads to IO (batteries included)
builddeps  :
    - haskell-async-devel
    - haskell-cabal-install
    - haskell-unliftio-core-devel
rundeps    :
    - devel:
        - haskell-async-devel
        - haskell-unliftio-core-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
